genmeta/gm-quic

qbase/src/token.rs

Add token unit test and make slight changes to put_reset_token

test(qbase): token unit test

---

qudp/src/unix.rs

This makes it clearer whether the number of messages or the size of the message is returned.

refactor(qudp): recvmsg returns enum instead of tuple

---

qconnection/src/auto.rs
qconnection/src/connection.rs
qconnection/src/transmit.rs
qrecovery/src/crypto.rs
qrecovery/src/space.rs
qrecovery/src/streams.rs
qrecovery/src/streams/data.rs
qrecovery/src/streams/none.rs

refactor(qrecovery, qconnection): remove Transmit traits

---

qconnection/src/path/validate.rs

https://github.com/genmeta/gm-quic/pull/31#pullrequestreview-2150322806  
不太确定是不是这么操作

refactor(qconnection): validate use timeout instead sleep

---

qrecovery/src/recv/rcvbuf.rs

fix(qrecovery): fix overlap_seg and try_append

---

qconnection/src/path.rs
qconnection/src/path/anti_amplifier.rs

Remove the amount parameter and directly return the remaining credit
amount when applying. If None is returned, it means that the path has
been verified and there is no protection against amplification attacks.

feat(qconnection): anti_amplifier poll apply return option

---

qconnection/src/auto.rs

fix(qconnection): fix generic_dispatch epoch

---

qbase/src/frame.rs
qbase/src/frame/error.rs
qbase/src/frame/io.rs
qconnection/src/connection/closing.rs
qconnection/src/connection/raw.rs
qrecovery/src/reliable.rs
qrecovery/src/space.rs

refactor: rename some name, include variable and struct name

---

qcongestion/src/congestion.rs
qconnection/src/connection/transmit/data.rs
qconnection/src/connection/transmit/handshake.rs
qconnection/src/connection/transmit/initial.rs

fix(congestion): fix record ack when recv pakcet
fix(qconnection): fix encode header

fix(congestion): fix record ack when recv pakcet

---

qbase/src/util.rs
qbase/src/util/async_cell.rs

写到传输参数发现我又得写一遍这个...RecvBuffer，CidState，ConnErr，已经有 好几个了，直接抽出来一个组件吧

feat(qbase): new util: AsyncCell

---

qconnection/src/connection.rs
qrecovery/src/recv.rs
qrecovery/src/recv/incoming.rs
qrecovery/src/recv/reader.rs
qrecovery/src/recv/recver.rs
qrecovery/src/send.rs
qrecovery/src/send/outgoing.rs
qrecovery/src/send/sender.rs
qrecovery/src/send/writer.rs
qrecovery/src/streams.rs
qrecovery/src/streams/data.rs
qrecovery/src/streams/listener.rs

feat: finish DataStreams

---

.github/workflows/rust.yml

ci: comment cargo doc ci

---

.github/workflows/rust.yml
qbase/src/packet/encrypt.rs
qbase/src/packet/header/short.rs
qbase/src/util/future.rs
qconnection/src/error.rs

docs(qbase): document util::Future, fix clippy warns

---

.github/workflows/rust.yml
qconnection/src/connection/transmit/initial.rs

https://github.com/rust-lang/rust-clippy/issues/13457 has closed

ci: use nightly clippy for stricter lint

---

.github/workflows/rust.yml
h3-shim/examples/h3-client.rs
h3-shim/examples/h3-server.rs
h3-shim/src/lib.rs
h3-shim/src/tests.rs
qconnection/src/path.rs
qudp/src/lib.rs
qudp/src/unix.rs

test: add http3 test

---

qrecovery/Cargo.toml
qrecovery/src/recv/rcvbuf.rs
qrecovery/src/recv/reader.rs
qrecovery/src/recv/recver.rs
qrecovery/src/send/writer.rs

比较早的时候就写了，最近才想起来
简化了RecvBuf，两层的设计太麻烦了，既不好读也不好维护，单层简单很多
avaliable性能略微变差，但是可以接受

perf(qrecovert): simplify recvbuf, reduce memory alloc

---

qbase/src/packet.rs
qconnection/src/path/burst.rs
qconnection/src/space/handshake.rs
qconnection/src/space/initial.rs
qconnection/src/tx.rs
qinterface/src/handy.rs
qrecovery/src/send/outgoing.rs
qrecovery/src/streams/raw.rs

fix(qinterface): fix usc delivering datagrams in reverse order

---

qcongestion/src/congestion.rs

问题背景
原有的逻辑是通过记录最新发送的 ACK frame 确认了哪些数据包，当 ACK frame 被确认时，才会 retire 这些数据包的 packet number (PN)。然而，当发生丢包时，确认的数据包可能不是连续的，导致接收队列无法向前滑动。这会导致后续的 ACK frame 携带大量已经确认过的 range。
修改
如果确认了 largest acked 的数据包，那么所有小于 largest acked 的数据包都会被 retire，包括那些未收到的数据包（发送方可能已经判定这些包丢失）。**这种逻辑在单路径传输中是有效的，但在多路径传输中，无法区分缺少的数据包是因为丢包还是被其他路径接收了。**

fix: retire loss packet

---

qcongestion/src/bbr.rs
qcongestion/src/new_reno.rs
qcongestion/src/rtt.rs

feat(qcongestion): emit RecoveryMetricsUpdated event

---

qbase/src/util/data.rs
qconnection/src/space.rs
qconnection/src/space/data.rs
qconnection/src/space/handshake.rs
qconnection/src/space/initial.rs
qconnection/src/tx.rs
qlog/Cargo.toml
qlog/src/legacy.rs
qlog/src/lib.rs
qlog/src/quic.rs
qlog/src/telemetry.rs
qlog/src/telemetry/handy.rs

feat: filter to control the generation of qlog events and raw info data

---

qbase/src/flow.rs

删掉的这个断言不正确，多线程下会panic。虽然是debug_assert吧，但是和Reader和Writer的debug_assert一样挺干扰调试，不如删掉
改了之后RecvController和SendController彻底不对齐了，RecvController彻底没了Err/Close状态，这是不好的方面
SendController有充分理由有Err，因为它要返回Err。那为了对齐，也为RecvController也写一个Result吗？

refactor: remove is_closed field of RecvController

---

gm-quic/src/tests.rs
qbase/src/frame.rs
qbase/src/frame/io.rs
qbase/src/net/tx.rs
qbase/src/packet.rs
qcongestion/src/congestion.rs
qcongestion/src/lib.rs
qconnection/src/builder.rs
qconnection/src/events.rs
qconnection/src/path.rs
qconnection/src/path/burst.rs
qconnection/src/path/idle.rs
qconnection/src/space/data.rs
qconnection/src/space/handshake.rs
qconnection/src/space/initial.rs
qconnection/src/tx.rs
qrecovery/src/crypto.rs
qrecovery/src/send/outgoing.rs
qrecovery/src/send/sender.rs
qrecovery/src/streams/raw.rs

feat: send ping packet

---

qconnection/src/space/data.rs
qconnection/src/space/handshake.rs
qconnection/src/space/initial.rs

fix: cc deadlock

---

qbase/src/param/util.rs

fix(qbase): fixed parse reset token as varint

---

gm-quic/src/tests.rs
interop/run_endpoint.sh
qconnection/src/builder.rs
qconnection/src/lib.rs
qconnection/src/path/burst.rs
qconnection/src/path/paths.rs
qconnection/src/space/data.rs
qconnection/src/space/handshake.rs
qconnection/src/space/initial.rs
qconnection/src/state.rs
qconnection/src/termination.rs

fixed do not send packets with ccf

feat(qconnection): add api for waiting for handshake and termination

---

.github/workflows/interop.yml

没测试，不一定能运行。ci得合并进去之后才可以手动触发，所以先合，再找和修问题

ci: interop ci

---

.github/workflows/rust.yml
Cargo.toml
README.md
README_CN.md
gm-quic/src/client.rs
gm-quic/src/interfaces.rs
gm-quic/src/lib.rs
gm-quic/src/server.rs
gm-quic/src/tests.rs
h3-shim/src/tests.rs
qbase/src/frame/max_streams.rs
qbase/src/param/util.rs
qconnection/src/path/idle.rs
qconnection/src/space/data.rs
qconnection/src/space/handshake.rs
qconnection/src/space/initial.rs
qconnection/src/tx.rs
qevent/src/lib.rs
qevent/src/quic.rs
qrecovery/src/streams/raw.rs
qudp/src/windows.rs

refactor: rollback msrv to 1.75

---

gm-quic/Cargo.toml
gm-quic/examples/echo-client.rs
gm-quic/examples/http-client.rs

feat: add progress bar and file transfer to echo client

---

qcongestion/src/congestion.rs
qcongestion/src/status.rs
qconnection/src/path.rs

fix: deadlock on ServerHello lost
